import type { SkyEntry } from "@/lib/experience/registry";

/**
 * Photographed skies for tours, all public domain or CC0: Poly Haven and ambientCG
 * skies, and NASA's Deep Star Maps turned into the night sky seen from a latitude.
 * Made by scripts/skies/build.py and hosted in the spacery-static bucket; regenerate
 * this list with its --ts flag.
 */
export const spacerySkies: SkyEntry[] = [
  {id: "clear-noon", label: "Clear noon", kind: "day", description: "A cloudless blue sky with the sun high overhead.", place: "Drakensberg foothills, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/clear-noon/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/clear-noon/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/clear-noon/thumb.jpg", light: "#fbfcff", sun: [0.6044, 0.2234], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/qwantani_noon_puresky"},
  {id: "fair-clouds", label: "Fair weather clouds", kind: "day", description: "Bright midday sun with scattered white clouds.", place: "Johannesburg, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/fair-clouds/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/fair-clouds/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/fair-clouds/thumb.jpg", light: "#ffffff", sun: [0.5951, 0.2419], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/kloofendal_48d_partly_cloudy_puresky"},
  {id: "summer-cumulus", label: "Summer cumulus", kind: "day", description: "Puffy summer clouds across a deep blue sky.", image: "https://storage.googleapis.com/spacery-static/skies/summer-cumulus/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/summer-cumulus/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/summer-cumulus/thumb.jpg", light: "#fffdf7", sun: [0.6027, 0.26], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/sunflowers_puresky"},
  {id: "alpine-clear", label: "Alpine clear", kind: "day", description: "Thin mountain air, a hard sun and a clean blue dome.", place: "Pizzo Pernice, Italian Alps", image: "https://storage.googleapis.com/spacery-static/skies/alpine-clear/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/alpine-clear/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/alpine-clear/thumb.jpg", light: "#fdfeff", sun: [0.6073, 0.2053], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/pizzo_pernice_puresky"},
  {id: "bright-midday", label: "Bright midday", kind: "day", description: "A crisp midday sky with a few wisps of cloud.", place: "Johannesburg, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/bright-midday/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/bright-midday/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/bright-midday/thumb.jpg", light: "#fbfdff", sun: [0.6019, 0.262], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/kloofendal_43d_clear_puresky"},
  {id: "high-clouds", label: "High broken clouds", kind: "day", description: "A soft sun behind high, broken coastal clouds.", place: "Namaqualand coast, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/high-clouds/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/high-clouds/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/high-clouds/thumb.jpg", light: "#fffffd", sun: [0.6183, 0.2336], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/aristea_wreck_puresky"},
  {id: "island-clouds", label: "Island clouds", kind: "day", description: "Flat-bottomed North Sea clouds in a blue sky.", place: "Borkum, Germany", image: "https://storage.googleapis.com/spacery-static/skies/island-clouds/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/island-clouds/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/island-clouds/thumb.jpg", light: "#fffffe", sun: [0.5011, 0.2424], credit: "ambientCG (CC0)", source: "https://ambientcg.com/a/DaySkyHDRI054B"},
  {id: "towering-clouds", label: "Towering clouds", kind: "day", description: "Big bright cumulus building up through the afternoon.", image: "https://storage.googleapis.com/spacery-static/skies/towering-clouds/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/towering-clouds/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/towering-clouds/thumb.jpg", light: "#fffffe", sun: [0.5555, 0.2273], credit: "ambientCG (CC0)", source: "https://ambientcg.com/a/DaySkyHDRI007B"},
  {id: "clear-morning", label: "Clear morning", kind: "day", description: "A clear mid-morning sky with the sun still climbing.", place: "Drakensberg foothills, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/clear-morning/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/clear-morning/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/clear-morning/thumb.jpg", light: "#fbfcff", sun: [0.6039, 0.2776], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/qwantani_mid_morning_puresky"},
  {id: "hazy-midday", label: "Hazy midday", kind: "day", description: "Warm, hazy farmland light with thin cloud.", place: "Limpopo, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/hazy-midday/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/hazy-midday/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/hazy-midday/thumb.jpg", light: "#fffdfb", sun: [0.6005, 0.2156], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/farm_field_puresky"},
  {id: "overcast", label: "Overcast", kind: "cloudy", description: "An even gray sky with soft light and no shadows.", place: "Johannesburg, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/overcast/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/overcast/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/overcast/thumb.jpg", light: "#e0dfdc", sun: [0.601, 0.3718], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/kloofendal_overcast_puresky"},
  {id: "misty-morning", label: "Misty morning", kind: "cloudy", description: "Cool white mist with the sun hidden behind it.", place: "Johannesburg, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/misty-morning/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/misty-morning/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/misty-morning/thumb.jpg", light: "#e0e0e0", credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/kloofendal_misty_morning_puresky"},
  {id: "winter-overcast", label: "Winter overcast", kind: "cloudy", description: "A low winter sky over snow, pale and quiet.", place: "Sumy, Ukraine", image: "https://storage.googleapis.com/spacery-static/skies/winter-overcast/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/winter-overcast/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/winter-overcast/thumb.jpg", light: "#e0dcd4", sun: [0.6183, 0.4045], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/snow_field_puresky"},
  {id: "thunderhead", label: "Thunderhead", kind: "storm", description: "A dark storm cloud building in a bright sky.", image: "https://storage.googleapis.com/spacery-static/skies/thunderhead/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/thunderhead/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/thunderhead/thumb.jpg", light: "#b0b2b2", credit: "ambientCG (CC0)", source: "https://ambientcg.com/a/DaySkyHDRI061B"},
  {id: "storm-at-dusk", label: "Storm at dusk", kind: "storm", description: "Heavy storm clouds with the last light breaking under them.", image: "https://storage.googleapis.com/spacery-static/skies/storm-at-dusk/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/storm-at-dusk/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/storm-at-dusk/thumb.jpg", light: "#b2b0ab", sun: [0.5045, 0.4641], credit: "ambientCG (CC0)", source: "https://ambientcg.com/a/EveningSkyHDRI030A"},
  {id: "rainy-evening", label: "Rainy evening", kind: "storm", description: "Low rain clouds rolling in at the end of the day.", image: "https://storage.googleapis.com/spacery-static/skies/rainy-evening/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/rainy-evening/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/rainy-evening/thumb.jpg", light: "#b1b2b2", sun: [0.7704, 0.4636], credit: "ambientCG (CC0)", source: "https://ambientcg.com/a/EveningSkyHDRI029B"},
  {id: "dawn", label: "Dawn", kind: "sunrise", description: "The pale glow on the horizon before the sun is up.", place: "Drakensberg foothills, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/dawn/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/dawn/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/dawn/thumb.jpg", light: "#e0cfb5", credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/qwantani_dawn_puresky"},
  {id: "clear-sunrise", label: "Clear sunrise", kind: "sunrise", description: "The sun just clearing a cloudless horizon.", place: "Drakensberg foothills, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/clear-sunrise/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/clear-sunrise/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/clear-sunrise/thumb.jpg", light: "#e0bb93", credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/qwantani_sunrise_puresky"},
  {id: "cape-town-sunrise", label: "Cape Town sunrise", kind: "sunrise", description: "A bright sunrise with streaks of high cloud.", place: "Table Mountain, Cape Town", image: "https://storage.googleapis.com/spacery-static/skies/cape-town-sunrise/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/cape-town-sunrise/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/cape-town-sunrise/thumb.jpg", light: "#d9e0d8", sun: [0.6385, 0.4407], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/table_mountain_1_puresky"},
  {id: "swabian-sunrise", label: "Swabian sunrise", kind: "sunrise", description: "Soft warm sunrise light through layered cloud.", place: "Swabian Jura, Germany", image: "https://storage.googleapis.com/spacery-static/skies/swabian-sunrise/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/swabian-sunrise/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/swabian-sunrise/thumb.jpg", light: "#e0c492", sun: [0.5983, 0.4695], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/drackenstein_quarry_puresky"},
  {id: "foggy-sunrise", label: "Foggy sunrise", kind: "sunrise", description: "A pink sun glowing through ground fog.", image: "https://storage.googleapis.com/spacery-static/skies/foggy-sunrise/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/foggy-sunrise/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/foggy-sunrise/thumb.jpg", light: "#e0b69c", sun: [0.528, 0.4695], credit: "ambientCG (CC0)", source: "https://ambientcg.com/a/MorningSkyHDRI007B"},
  {id: "golden-afternoon", label: "Golden afternoon", kind: "sunset", description: "A low warm sun late in a clear afternoon.", place: "Free State, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/golden-afternoon/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/golden-afternoon/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/golden-afternoon/thumb.jpg", light: "#d6dbd0", credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/lonely_road_afternoon_puresky"},
  {id: "sunset", label: "Sunset", kind: "sunset", description: "A warm sunset under a few lit clouds.", place: "Drakensberg foothills, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/sunset/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/sunset/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/sunset/thumb.jpg", light: "#dbbc87", sun: [0.6034, 0.4924], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/qwantani_sunset_puresky"},
  {id: "sunset-over-water", label: "Sunset over water", kind: "sunset", description: "A calm, lilac sunset with the sun on the horizon.", place: "Belfast, Mpumalanga, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/sunset-over-water/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/sunset-over-water/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/sunset-over-water/thumb.jpg", light: "#dbc39f", credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/belfast_sunset_puresky"},
  {id: "golden-clouds", label: "Golden clouds", kind: "sunset", description: "Evening clouds lit gold and orange from below.", image: "https://storage.googleapis.com/spacery-static/skies/golden-clouds/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/golden-clouds/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/golden-clouds/thumb.jpg", light: "#dbd0be", sun: [0.5001, 0.467], credit: "ambientCG (CC0)", source: "https://ambientcg.com/a/EveningSkyHDRI032B"},
  {id: "clear-sunset", label: "Clear sunset", kind: "sunset", description: "A soft orange glow along a clear horizon.", place: "Rosendal, Free State, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/clear-sunset/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/clear-sunset/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/clear-sunset/thumb.jpg", light: "#dbc1ae", credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/rosendal_park_sunset_puresky"},
  {id: "steppe-sunrise", label: "Steppe sunrise", kind: "sunrise", description: "Feathery clouds over open steppe at sunrise.", place: "Poltava steppe, Ukraine", image: "https://storage.googleapis.com/spacery-static/skies/steppe-sunrise/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/steppe-sunrise/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/steppe-sunrise/thumb.jpg", light: "#e0c3a0", sun: [0.5992, 0.4104], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/scythian_tombs_puresky"},
  {id: "dusk", label: "Dusk", kind: "dusk", description: "The sun just gone, a warm band under a cooling sky.", place: "Drakensberg foothills, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/dusk/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/dusk/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/dusk/thumb.jpg", light: "#a891a4", credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/qwantani_dusk_2_puresky"},
  {id: "blue-hour", label: "Blue hour", kind: "dusk", description: "Deep blue twilight with a last pale glow.", image: "https://storage.googleapis.com/spacery-static/skies/blue-hour/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/blue-hour/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/blue-hour/thumb.jpg", light: "#909da8", sun: [0.5011, 0.4895], credit: "ambientCG (CC0)", source: "https://ambientcg.com/a/EveningSkyHDRI042B"},
  {id: "milky-way", label: "Milky Way", kind: "night", description: "A clear dark night with the Milky Way overhead.", place: "Drakensberg foothills, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/milky-way/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/milky-way/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/milky-way/thumb.jpg", light: "#3e4b75", credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/qwantani_night_puresky"},
  {id: "moonlit-stars", label: "Moonlit stars", kind: "night", description: "Stars and a bright moon in a clear sky.", place: "Mpumalanga, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/moonlit-stars/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/moonlit-stars/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/moonlit-stars/thumb.jpg", light: "#4d5e93", sun: [0.5988, 0.4011], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/kloppenheim_02_puresky"},
  {id: "moonrise", label: "Moonrise", kind: "night", description: "The moon rising over the horizon among stars.", place: "Drakensberg foothills, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/moonrise/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/moonrise/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/moonrise/thumb.jpg", light: "#4d5e93", sun: [0.6, 0.4226], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/qwantani_moonrise_puresky"},
  {id: "cloudy-night", label: "Cloudy night", kind: "night", description: "Moonlight breaking through a low, cloudy night.", place: "Mpumalanga, South Africa", image: "https://storage.googleapis.com/spacery-static/skies/cloudy-night/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/cloudy-night/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/cloudy-night/thumb.jpg", light: "#4d5e93", sun: [0.6049, 0.28], credit: "Poly Haven (CC0)", source: "https://polyhaven.com/a/kloppenheim_07_puresky"},
  {id: "galactic-core", label: "Galactic core", kind: "night", description: "The bright core of the Milky Way arching across the sky.", image: "https://storage.googleapis.com/spacery-static/skies/galactic-core/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/galactic-core/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/galactic-core/thumb.jpg", light: "#3e4b75", credit: "ambientCG (CC0)", source: "https://ambientcg.com/a/NightSkyHDRI008"},
  {id: "full-moon", label: "Full moon", kind: "night", description: "A full moon high in a starry sky.", image: "https://storage.googleapis.com/spacery-static/skies/full-moon/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/full-moon/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/full-moon/thumb.jpg", light: "#4d5e93", sun: [0.4999, 0.2502], credit: "ambientCG (CC0)", source: "https://ambientcg.com/a/NightSkyHDRI003"},
  {id: "northern-lights", label: "Northern lights", kind: "night", description: "Curtains of aurora over a starry sky.", image: "https://storage.googleapis.com/spacery-static/skies/northern-lights/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/northern-lights/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/northern-lights/thumb.jpg", light: "#4d5e93", sun: [0.4999, 0.2], credit: "ambientCG (CC0)", source: "https://ambientcg.com/a/NightSkyHDRI004"},
  {id: "northern-stars", label: "Northern stars", kind: "night", description: "Every star and the Milky Way as seen from the Mediterranean on a summer night.", place: "Seen from 38 degrees north", image: "https://storage.googleapis.com/spacery-static/skies/northern-stars/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/northern-stars/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/northern-stars/thumb.jpg", light: "#3e4b75", credit: "NASA Goddard Scientific Visualization Studio (public domain)", source: "https://svs.gsfc.nasa.gov/4851"},
  {id: "southern-stars", label: "Southern stars", kind: "night", description: "The southern sky with the Milky Way's core overhead.", place: "Seen from 30 degrees south", image: "https://storage.googleapis.com/spacery-static/skies/southern-stars/4k.jpg", preview: "https://storage.googleapis.com/spacery-static/skies/southern-stars/1k.jpg", thumb: "https://storage.googleapis.com/spacery-static/skies/southern-stars/thumb.jpg", light: "#3e4b75", credit: "NASA Goddard Scientific Visualization Studio (public domain)", source: "https://svs.gsfc.nasa.gov/4851"},
];
